
-- DATA VALIDATION 
-- Any data where order was returned but payment status not updated 
SELECT o.order_status,
       p.payment_status,
       COUNT(*)
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
GROUP BY o.order_status, p.payment_status
ORDER BY o.order_status;

UPDATE payments p
SET payment_status = 'Refunded'
FROM orders o
WHERE p.order_id = o.order_id
AND o.order_status = 'Returned';

--Cancelled orders still shipped
SELECT
    o.order_id,
    o.order_status,
    s.delivery_status,
    s.shipping_date
FROM orders o
JOIN shipping s
    ON o.order_id = s.order_id
WHERE o.order_status = 'Cancelled'
  AND s.delivery_status IN ('Shipped', 'Delivered', 'In Transit');

--Inventory products missing from products table
SELECT
    i.inventory_id,
    i.product_id,
    i.stock_remaining,
    i.ware_house_id,
    i.restock_date
FROM inventory i
LEFT JOIN products p
    ON i.product_id = p.product_id
WHERE p.product_id IS NULL;

-- NO DATA DISCREPENCIES FOUND 

--QUERYING DATA FOR INSIGHTS  

/* 1) Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.*/

--(MAKING A SAFE CHECK)finding products that were not order if any(none exist )
SELECT
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN order_items oi
    ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

SELECT 
oi.product_id,
p.product_name,
SUM(oi.total_price) as total_sale,
COUNT(o.order_id) as total_orders
FROM orders as o
JOIN
order_items as oi
ON oi.order_id=o.order_id
JOIN
products as p
ON p.product_id=oi.product_id
GROUP BY 1,2 
ORDER BY 3 DESC
LIMIT 10;

/* 2)Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.*/

SELECT 
   p.category_id,
   c.category_name,
   SUM(oi.total_price) AS total_sale,
   SUM(oi.total_price) * 100.0 / (SELECT SUM(total_price) FROM order_items) AS contribution
   FROM order_items AS oi
   JOIN products AS p ON p.product_id = oi.product_id
   LEFT JOIN category AS c ON c.category_id = p.category_id
   GROUP BY 1, 2
   ORDER BY 3 DESC;

/* 3)Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.*/

SELECT 
   c.customer_id,
   CONCAT(c.f_name, ' ', c.l_name) AS full_name,
   SUM(total_price) / COUNT(DISTINCT o.order_id) AS AOV,
   COUNT(DISTINCT o.order_id) AS total_orders
   FROM orders AS o
   JOIN customers AS c ON c.customer_id = o.customer_id
   JOIN order_items AS oi ON oi.order_id = o.order_id
   GROUP BY 1, 2
   HAVING COUNT(DISTINCT o.order_id) > 5;

/*WITH order_values AS (
    SELECT
        o.order_id,
        o.customer_id,
        SUM(oi.total_price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id
)

SELECT
    c.customer_id,
    CONCAT(c.f_name, ' ', c.l_name) AS full_name,
    AVG(ov.order_value) AS avg_order_value,
    COUNT(*) AS total_orders
FROM order_values ov
JOIN customers c
    ON c.customer_id = ov.customer_id
GROUP BY c.customer_id, full_name
HAVING COUNT(*) > 5;*/

 /* 4)Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Return current month sale and last month sale.*/

 SELECT 
   year,
   month,
   total_sale AS current_month_sale,
   LAG(total_sale, 1) OVER (ORDER BY year, month) AS last_month_sale
 FROM (
   SELECT 
     EXTRACT(YEAR FROM o.order_date) AS year,
     EXTRACT(MONTH FROM o.order_date) AS month,
     ROUND(SUM(oi.total_price::numeric), 2) AS total_sale
   FROM orders AS o
   JOIN order_items AS oi ON oi.order_id = o.order_id
   WHERE o.order_date >= CURRENT_DATE - INTERVAL '1 year'
   GROUP BY 1, 2
   ORDER BY year, month
 ) AS t1;

/* 5)Customers with No Purchases
Find customers who registered but never placed an order.
*/

SELECT *
 FROM customers
 WHERE customer_id NOT IN (
   SELECT DISTINCT customer_id FROM orders
 );

/* 6)Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.*/

WITH ranking_table AS (
   SELECT 
     c.state,
     cat.category_name,
     SUM(oi.total_price) AS total_sale,
     RANK() OVER (PARTITION BY c.state ORDER BY SUM(oi.total_price) ASC) AS rnk
   FROM orders AS o
   JOIN customers AS c ON o.customer_id = c.customer_id
   JOIN order_items AS oi ON o.order_id = oi.order_id
   JOIN products AS p ON oi.product_id = p.product_id
   JOIN category AS cat ON cat.category_id = p.category_id
   GROUP BY 1, 2
 )
 SELECT *
 FROM ranking_table
 WHERE rnk = 1;

/*7)Customer Lifetime Value (CLTV)
Rank customers by CLTV.*/

 SELECT 
   c.customer_id,
   CONCAT(c.f_name, ' ', c.l_name) AS full_name,
   SUM(total_price) AS CLTV,
   DENSE_RANK() OVER (ORDER BY SUM(total_price) DESC) AS cx_ranking
 FROM orders AS o
 JOIN customers AS c ON c.customer_id = o.customer_id
 JOIN order_items AS oi ON oi.order_id = o.order_id
 GROUP BY 1, 2;

/*8)Inventory Stock Alerts
Products with stock < 100; include last restock and warehouse.*/


 SELECT 
   i.inventory_id,
   p.product_name,
   i.stock_remaining,
   i.restock_date,
   i.ware_house_id
 FROM inventory AS i
 JOIN products AS p ON p.product_id = i.product_id
 WHERE i.stock_remaining < 100;

/*9)Shipping Delays
Orders where shipping date is > 3 days after order date.*/

 SELECT 
   c.*,
   o.*,
   s.shipping_date - o.order_date AS days_took_to_ship
 FROM orders AS o
 JOIN customers AS c ON c.customer_id = o.customer_id
 JOIN shipping AS s ON o.order_id = s.order_id
 WHERE s.shipping_date - o.order_date > 3;

/*10)Payment Success Rate
Percentage by payment status.*/

SELECT 
  p.payment_status,
  COUNT(*) AS total_cnt,
  COUNT(*)::numeric / (SELECT COUNT(*) FROM payments)::numeric * 100 AS pct
FROM orders AS o
JOIN payments AS p ON o.order_id = p.order_id
GROUP BY 1;

/*11)Top Performing Sellers
Top 5 sellers by sales; include success %.*/

WITH top_sellers AS
(
    SELECT
        s.seller_id,
        s.seller_name,
        SUM(oi.total_price) AS total_sales
    FROM sellers s
    JOIN products p
        ON p.seller_id = s.seller_id
    JOIN order_items oi
        ON oi.product_id = p.product_id
    GROUP BY
        s.seller_id,
        s.seller_name
    ORDER BY total_sales DESC
    LIMIT 5
), seller_orders AS
(
    SELECT
        ts.seller_id,
        ts.seller_name,
        o.order_status,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM top_sellers ts
    JOIN products p
        ON p.seller_id = ts.seller_id
    JOIN order_items oi
        ON oi.product_id = p.product_id
    JOIN orders o
        ON o.order_id = oi.order_id
    WHERE o.order_status NOT IN ('Pending','Returned','Shipped')
    GROUP BY
        ts.seller_id,
        ts.seller_name,
        o.order_status
)
SELECT
    seller_id,
    seller_name,

    SUM(
        CASE
            WHEN order_status='Delivered'
            THEN total_orders
            ELSE 0
        END
    ) AS completed_orders,

    SUM(total_orders) AS total_orders,

    ROUND(
        SUM(
            CASE
                WHEN order_status='Delivered'
                THEN total_orders
                ELSE 0
            END
        )::numeric
        /
        SUM(total_orders)
        *100,
        2
    ) AS success_percentage

FROM seller_orders
GROUP BY
    seller_id,
    seller_name
	ORDER BY success_percentage DESC;
	
/* 12)Product Profit Margin
Rank products by profit margin (highest → lowest).*/

SELECT 
  product_id,
  product_name,
  profit_margin,
  DENSE_RANK() OVER (ORDER BY profit_margin DESC) AS product_ranking
FROM (
  SELECT 
    p.product_id,
    p.product_name,
    SUM(total_price - (p.cogs * oi.quantity)) / SUM(total_price) * 100 AS profit_margin
  FROM order_items AS oi
  JOIN products AS p ON oi.product_id = p.product_id
  GROUP BY 1, 2
) AS t1;

/* 13)Most Returned Products
Top 10 products by return rate.*/

SELECT 
  p.product_id,
  p.product_name,
  COUNT(*) AS total_unit_sold,
  SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returned,
  SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END)::numeric
    / COUNT(*)::numeric * 100 AS return_percentage
FROM order_items AS oi
JOIN products AS p ON oi.product_id = p.product_id
JOIN orders AS o ON o.order_id = oi.order_id
GROUP BY 1, 2
ORDER BY 5 DESC
LIMIT 10;

/* 14)Inactive Sellers
Sellers with no sales in the last  month; show last sale date & amount.*/

WITH seller_sales AS (
    SELECT
        p.seller_id,
        o.order_date,
        oi.total_price,
        ROW_NUMBER() OVER (
            PARTITION BY p.seller_id
            ORDER BY o.order_date DESC
        ) AS rn
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
),
inactive_sellers AS (
    SELECT seller_id
    FROM seller_sales
    GROUP BY seller_id
    HAVING MAX(order_date) < CURRENT_DATE - INTERVAL '1 month'
)
SELECT
    ss.seller_id,
    ss.order_date AS last_sale_date,
    ss.total_price AS last_sale_amount
FROM seller_sales ss
JOIN inactive_sellers i
    ON ss.seller_id = i.seller_id
WHERE ss.rn = 1;

/* 15)Identify returning vs. new customers
If a customer has > 5 returns → returning; else new.
Challenge: List customer name, total orders, total returns.*/

SELECT 
  c_full_name AS customers,
  total_orders,
  total_return,
  CASE WHEN total_return > 5 THEN 'Returning_customers' ELSE 'New' END AS cx_category
FROM (
  SELECT 
    CONCAT(c.f_name, ' ', c.l_name) AS c_full_name,
    COUNT(o.order_id) AS total_orders,
    SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_return	
  FROM orders AS o
  JOIN customers AS c ON c.customer_id = o.customer_id
  JOIN order_items AS oi ON oi.order_id = o.order_id
  GROUP BY 1
) AS t;

/* 16)Top 5 Customers by Orders in Each State
Include number of orders and total sales per customer.*/

SELECT * FROM (
  SELECT 
    c.state,
    CONCAT(c.f_name, ' ', c.l_name) AS customers,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(total_price) AS total_sale,
    DENSE_RANK() OVER (
    PARTITION BY c.state
    ORDER BY COUNT(DISTINCT o.order_id) DESC,
             SUM(oi.total_price) DESC
    ) AS rnk
  FROM orders AS o
  JOIN order_items AS oi ON oi.order_id = o.order_id
  JOIN customers AS c ON c.customer_id = o.customer_id
  GROUP BY 1, 2
) AS t1
WHERE rnk <= 5;

/* 17)Customer Retention Rate
Find custom*/

SELECT
    p.product_name,
    SUM(oi.total_price) revenue,
    ROUND(
      100 * SUM(oi.total_price)
      / SUM(SUM(oi.total_price)) OVER(),
      2
    ) AS contribution_pct
FROM products p
JOIN order_items oi
    ON p.product_id=oi.product_id
GROUP BY 1
ORDER BY revenue DESC;

/* 18)Products with highest YoY revenue decrease (2024 → 2025)
Return product details and decrease ratio.*/

SELECT
    p.product_id,
    p.product_name,
    SUM(CASE WHEN EXTRACT(YEAR FROM o.order_date) = 2024
             THEN oi.total_price ELSE 0 END) AS revenue_2024,
    SUM(CASE WHEN EXTRACT(YEAR FROM o.order_date) = 2025
             THEN oi.total_price ELSE 0 END) AS revenue_2025
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name;

 /* 19) RFM Query
 Measures:

Recency → last purchase
Frequency → number of orders
Monetary → money spent*/

SELECT
    customer_id,
    CURRENT_DATE - MAX(order_date) AS recency,
    COUNT( DISTINCT o.order_id) AS frequency,
    SUM(oi.total_price) AS monetary
FROM orders o
JOIN order_items oi
    ON o.order_id=oi.order_id
GROUP BY customer_id;

/* 20)Stored Procedure: record sale & update inventory
Inserts into orders and order_items; decrements inventory.*/

CREATE OR REPLACE PROCEDURE add_sales
(
  p_order_id INT,
  p_customer_id INT,
  p_seller_id INT,
  p_order_item_id INT,
  p_product_id INT,
  p_quantity INT
)
LANGUAGE plpgsql
AS $$
DECLARE 
  v_count INT;
  v_price FLOAT;
  v_product VARCHAR(50);
BEGIN
  SELECT price, product_name INTO v_price, v_product
  FROM products
  WHERE product_id = p_product_id;
    
  SELECT COUNT(*) INTO v_count
  FROM inventory
  WHERE product_id = p_product_id
    AND stock >= p_quantity;
    
  IF v_count > 0 THEN
    INSERT INTO orders(order_id, order_date, customer_id, seller_id)
    VALUES (p_order_id, CURRENT_DATE, p_customer_id, p_seller_id);
    
    INSERT INTO order_items(order_item_id, order_id, product_id, quantity, price_per_unit, total_sale)
    VALUES (p_order_item_id, p_order_id, p_product_id, p_quantity, v_price, v_price * p_quantity);
    
    UPDATE inventory
    SET stock = stock - p_quantity
    WHERE product_id = p_product_id;
    
    RAISE NOTICE 'Product % sale added; inventory updated', v_product; 
  ELSE
    RAISE NOTICE 'Product % is not available', v_product;
  END IF;
END;
$$;










  












